version: "3.9"

services:
  judge0:
    build: ./Judge
    container_name: code-judge
    ports:
      - "7001:7001"
    volumes:
      - ./Judge:/app
      - /app/node_modules
    # 💡 It's better to give Judge its own .env to avoid confusion
    env_file:
      - ./Judge/.env 
    networks:
      codebench-network:
        aliases:
          - code-judge

  backend:
    build: ./Backend
    container_name: codebench-backend
    ports:
      - "8000:8000"
    depends_on:
      - judge0
    volumes:
      - ./Backend:/app
      - /app/node_modules
    env_file:
      - ./Backend/.env
    networks:
      - codebench-network

networks:
  codebench-network:
    driver: bridge